// content of index.js
const main = require('./main');
const express = require('express');
const bodyParser = require('body-parser');
const expressServer = express();

expressServer.use(bodyParser.json());
expressServer.use(express.static('public'));

// TODO change this with your backend domain name
// the one generated by ngrok if you use ngrok
DOMAIN_URL = "https://my-domain-name-exemple";

expressServer.get('/', (req, res) => {
  main.requestHandler(req, res);
});

expressServer.post('/', (req, res) => {
  main.requestHandler(req, res);
});

expressServer.listen(3000, () => {
  console.log('Example app listening on port 3000!')
});